import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  async function handleOnSubmit(e) {
    e.preventDefault();
    const formData = {};
    Array.from(e.currentTarget.elements).forEach(field => {
      if (!field.name) return;
      formData[field.name] = field.value;
    })
    console.log(formData);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form method="post" onSubmit={handleOnSubmit}>
        <input name="username" type="text" placeholder="username"/>
        <input name="password" type="text" placeholder="password"/>
        <input type="submit"/>
      </form>
    </div>
  )
}
